let num = 4
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;

try {
    alert("Hello Everyone")
    num;
    num;
    num;
    // console.log(num / 0)
    throw "something wrong"

    console.log("console after error")
    num;
    num;
    num;
    num;
    num;
    num;
    num;

} catch (error) {
    console.log("Error : ", error)
}


num;
console.log("console after try catch");
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;
num;